build:
  version: 2.0

accounts:
  message: "Accounts Microservice - QA API's"
  contactDetails:
    name: "John Doe - QA Lead"
    email: "jdoe@me.com"
    mobile: "1234567890"
  onCallSupport:
    - (+91) 1234567890
    - (+91) 1234567891